cabal-version:      3.14
name:               TP-Bases
version:            0.1.0.0
license:            MIT
license-file:       LICENSE
author:             Lucas
maintainer:         90753591+lucasDS-0@users.noreply.github.com.
category:           Database
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall 
                 -Wcompat 
                 -Wincomplete-record-updates
                 -Wredundant-constraints
                 -Wmissing-export-lists
                 -Wunused-packages

executable TP-Bases
    import:           warnings
    main-is:          Main.hs
    other-modules:    DLLParser,
                      PKDetector,
                      HintParser,
                      QueryParser
    build-depends:    base ^>=4.20.2.0,
                      ghc-internal,
                      text,
                      bytestring,
                      aeson,
                      parsec,
                      simple-sql-parser
    hs-source-dirs:   app, src
    default-language: Haskell2010
